name: CI
on: [push, pull_request]
jobs:
  build_test:
    strategy:
      matrix:
        component:
        - rollup
        - webpack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npx lerna bootstrap
    - run: npm run prepack
      working-directory: packages/common
    - run: npm install
      working-directory: test/${{ matrix.component }}
    - run: npm run test:control
      working-directory: test/${{ matrix.component }}
    - run: npm run test:experimental
      working-directory: test/${{ matrix.component }}
    - run: ls -lh dist_control dist_experimental
      working-directory: test/${{ matrix.component }}

